# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Not issued'), (2, 'Issued'), (3, 'Expired')], default=1)),
                ('issued', models.DateTimeField(null=True)),
                ('expired', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
