# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keygen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
