# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keygen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='status',
            field=models.CharField(choices=[('status_free', 'Free to use'), ('status_issued', 'Issued'), ('status_expired', 'Expired')], default='status_free', max_length=20),
        ),
    ]
